{% set name = "aioftp" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94648d17dd3ca44614b59e8f795991b447258d82aa1b4cfecc0aceccf01b7495

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.5.3
  run:
    - python >=3.5.3

test:
  imports:
    - aioftp

about:
  home: http://aioftp.readthedocs.org/
  license: Apache 2
  license_family: APACHE
  license_file: license.txt
  summary: FTP client/server for Python asyncio
  dev_url: https://github.com/aio-libs/aioftp

extra:
  recipe-maintainers:
    - epruesse
