{% set name = "aioftp" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5711c03433b510c101e9337069033133cca19b508b5162b414bed24320de6c18

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.5.3
  run:
    - python >=3.5.3

test:
  imports:
    - aioftp

about:
  home: http://aioftp.readthedocs.org/
  license: Apache 2
  license_family: APACHE
  license_file: license.txt
  summary: FTP client/server for Python asyncio
  dev_url: https://github.com/aio-libs/aioftp

extra:
  recipe-maintainers:
    - epruesse
