travis:
  secure:
    BINSTAR_TOKEN: jFKrSacRJ3w52dC6QMUkdeTxYioFpD9fOB3Usf4+mvj/zNOpVyAT8Xp+HhTnYwlLysvHoeh4xvyBPTcXhjnT2A17zvOnHz4hC9tva2pqzc1RVVJwy5pbnuqXhbn+UZT7IeAauvsyH2krOVOrChpu/XU/Ga7tD2GOCNMeA5shAds5Hpi+Ggw3eF4CQg1gh/v8wCabf+iENwWg2k33JN4FEKgRjYAj8b0yIyudgkdrkp4fHaEH2aRgsPz8CBerU7k7psFo1JxJeLU5LjGy/QKkwX0RvB9mx76s8yzyV258UW/CAfiBfYsDIZMfkdlDTtp4t7OJPv5Khd1H8uZhqRYnLKz0qmSooWmtUZ+Y8jMuvVAhPw6jp7mGV3CNEr5UjKhaYu6u5iTwMJpsWES5DVbM7T8OwoxE4fJEz1m9uTIN64O/Gr/01aPr8tI3yqAcmquWebZ9DVz42Yf1GAiIn7TZAzIaWWN9JkjKBrjrrOLNYCtPjc3ExMbxT/8lyH1jYOV0xUpyr2rLyXCzfPdKmQcP+riSEogwfYv0lNwYX2uhnQpWnoVtxiY5lslkZ0PtS30M6fFQkd/dQCGaGVw+o4hrmruUm2Rzr3Y6ZKnIhM+DyBiU+bh5hVmVN6sago1pxteAD/vhlZuSZSAy7IXRBzB+Os16bWkDu37YXPnPgA70SBk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
